IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CALL_WOODLAND_BEINGS)  // SPPR410.SPL (Call Woodland Beings)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CALL_WOODLAND_BEINGS)  // SPPR410.SPL (Call Woodland Beings)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_ANIMAL_SUMMONING_1)  // SPPR402.SPL (Animal Summoning I)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ANIMAL_SUMMONING_1)  // SPPR402.SPL (Animal Summoning I)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
    AreaType(OUTDOOR)
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
END

IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
    HaveSpell(CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence 15' Radius)
    OR(2)
        See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
        Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence 15' Radius)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

