IF
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
    Global("prep","LOCALS",0)
THEN
    RESPONSE #100
        ApplySpell(Myself,CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
        SetGlobal("prep","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Chant)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CHANT)  // SPPR203.SPL (Chant)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HPPercentLT(LastSeenBy(Myself),60)
    HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
END

IF
    See(NearestEnemyOf(Myself))
    See(NearestMyGroupOfType)
    HPPercentLT(LastSeenBy(Myself),80)
    HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
END

IF
    See(NearestEnemyOf(Myself))
    HPPercentLT(Myself,60)
    HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
END

IF
    See(NearestEnemyOf(Myself))
    HPPercentLT(Myself,80)
    HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
END

IF
    See(NearestEnemyOf(Myself))
    !Range(LastSeenBy(Myself),4)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        AttackReevaluate(NearestEnemyOf(Myself),15)
END

