// Double-check that charname is in the right place
// to open the bandit camp ruins
IF
	IsOverMe([PC])
	Global("bs_ar1900","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bs_ar1900","MYAREA",1)
END

IF
	!IsOverMe([PC])
	Global("bs_ar1900","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("bs_ar1900","MYAREA",0)
END


IF
	Global("bsUsedAlmiranScroll","GLOBAL",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
//		ForceSpellRES("bs00002",Myself)
		FadeToColor([50.0],0)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("bs0128","",[452.2071],10))
		ActionOverride(Player2,LeaveAreaLUA("bs0128","",[468.2100],10))
		ActionOverride(Player3,LeaveAreaLUA("bs0128","",[405.2107],10))
		ActionOverride(Player4,LeaveAreaLUA("bs0128","",[447.2112],10))
		ActionOverride(Player5,LeaveAreaLUA("bs0128","",[355.2131],10))
		ActionOverride(Player6,LeaveAreaLUA("bs0128","",[389.2153],10))
		FadeFromColor([50.0],0)
		SetGlobal("bsUsedAlmiranScroll","GLOBAL",2)
		SetInterrupt(TRUE)
END

