/* water drips: collect fresh water here */

IF
	Clicked([ANYONE])
	Range(LastTrigger,20)
	Global("bs_CollectDrippingWater","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreatureObject("bsidrips",Player1,0,0,0)
		SetGlobal("bs_CollectDrippingWater","MYAREA",1)
END

IF
	InMyArea("bsidrips")
	Global("bs_CollectDrippingWater","MYAREA",1)
THEN
	RESPONSE #100
		ActionOverride("bsidrips",StartDialogueNoSet([PC]))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,20)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11007)
END

