// Book
/* for legacy reasons, this is a cutscene now. */
IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("bsDreamTrap","GLOBAL",1)
		SetGlobal("bsStartDream","GLOBAL",2)
		DisplayStringHead(Player1,@9314)
		FadeToColor([50.0],0)
		Wait(2)
		LeaveAreaLUAPanic("bs0157","",[193.311],14)
		ActionOverride("bsalgb2",DestroySelf())
		LeaveAreaLUA("bs0157","",[193.311],14)
		FadeFromColor([50.0],0)
		EndCutSceneMode()
END
