/* this is to open up Seatower */


// Unlock and prepare the area
IF
  GlobalLT("bsOpenSeatower","GLOBAL",2)
THEN
  RESPONSE #100
	SetInterrupt(FALSE)
	Unlock("DOOR 02")
	Unlock("DOOR 05")
	Unlock("DOOR 07")
//	Unlock("DOOR 08")
	Unlock("DOOR 13")
//	Unlock("DOOR 14")
	Unlock("DOOR 15") //Tannery door
	Unlock("DOOR 16")
	OpenDoor("DOOR 09") //main gates
	OpenDoor("DOOR 13")
	OpenDoor("DOOR 14")
	TriggerActivation("Travbs1010",TRUE)
	CreateCreature("ysstcgrd",[3804.1941],1)
	CreateCreature("ysstcgrd",[2781.1652],1) //Tower Guard in front of barracks
	CreateCreature("ysstcgrd",[1992.1258],15)  // Tower Guard in front of treasury
	CreateCreature("ysstcgrd",[1901.1212],1)  // Tower Guard in front of treasury
	CreateCreature("bsgrdbcn",[3732.554],6)
	CreateCreature("bsboybcn",[3599.522],0) 
	CreateCreature("bsmanbcn",[3504.518],0)
	CreateCreature("bswellgl",[3827.2108],3) 
	CreateCreature("bswellbo",[3804.2086],0) 
	CreateCreature("bswellma",[3845.2058],2) 
	AmbientActivate("GreenSmoke",FALSE)
	SetGlobal("bsOpenSeatower","GLOBAL",2)
	SetInterrupt(TRUE)
END

//make sure doors are open */
IF
  GlobalLT("bsOpenSeatower","GLOBAL",3)
THEN
  RESPONSE #100
	SetInterrupt(FALSE)
	Unlock("DOOR 02")
	Unlock("DOOR 05")
	Unlock("DOOR 07")
//	Unlock("DOOR 08")
	Unlock("DOOR 13")
//	Unlock("DOOR 14")
	Unlock("DOOR 15") //Tannery door
	Unlock("DOOR 16")
	OpenDoor("DOOR 09") //main gates
	OpenDoor("DOOR 13")
	OpenDoor("DOOR 14")
	TriggerActivation("Travbs1010",TRUE)
	SetGlobal("bsOpenSeatower","GLOBAL",3)
	SetInterrupt(TRUE)
END

/* 5th smuggler quest - spawn smuggler contact */
IF
	InMyArea(Player1)
	Global("bsSmugglerQuest","GLOBAL",22)
	!Dead("bssmgl02")
	Global("bs_SpawnSmugglerContact5","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bssmgl18",[3509.3130],8) //Smuggler Contact
		SetGlobal("bs_SpawnSmugglerContact5","MYAREA",1)
END

/* 5th smuggler quest, reporting smugglers to FF: timer expired, no barrel delivery. Spawn Tower Guard - in both bs1000 and bs1011 */
IF
	InMyArea(Player1)
	Global("bs_ReportSmugglersToSeatower","GLOBAL",6)
	GlobalGT("bsSmugglerQuest","GLOBAL",24)
	GlobalTimerExpired("bsSmugglerQuestTimer5","GLOBAL")
	!PartyHasItem("bssmq008")
	!Exists("bssmgl17")
	!Exists("bssmgl18")
	CombatCounter(0)
THEN
	RESPONSE #100
        SetInterrupt(FALSE)
		SetGlobal("bs_ReportSmugglersToSeatower","GLOBAL",7)
		CreateCreatureObjectOffset("bssmgl19",Player1,[10.5])
        SetInterrupt(TRUE)
END


/* spawn Lady & Young Lord Dlusker */
IF
	OR(2)
		!Global("Chapter","GLOBAL",%tutu_chapter_7%)
		!Global("DukeThanks","GLOBAL",0)
	Global("bs_SpawnDluskers","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bsrsd02",[1083.2063],0) //Lady Dlusker
		CreateCreature("bsrsd03",[1103.2021],0) //Young Lord Dlusker
		SetGlobal("bs_SpawnDluskers","MYAREA",1)
END

/* spawn Ivonne from Hidden Letters quest */
IF
	OR(2)
		!Global("Chapter","GLOBAL",%tutu_chapter_7%)
		!Global("DukeThanks","GLOBAL",0)
	Global("bs_HiddenLetters","GLOBAL",0)
THEN
	RESPONSE #100
		CreateCreature("bshdlet1",[1115.459],8) //Ivonne
		SetGlobal("bs_HiddenLetters","GLOBAL",1)
END
/* Ivonne comes again if letter(s) are gone */
IF
	Global("bs_HiddenLetters","GLOBAL",20)
THEN
	RESPONSE #100
		CreateCreature("bshdlet1",[1115.459],8) //Ivonne
		SetGlobal("bs_HiddenLetters","GLOBAL",21)
END

/*
/* deactivate triggers to bs1001.are. These are deprecated. */
IF
	Global("bsDeactivateTriggersbs1001","MYAREA",0)
THEN
	RESPONSE #100
		TriggerActivation("Yst6info",FALSE)
		TriggerActivation("bs1001t1",FALSE)
		SetGlobal("bsDeactivateTriggersbs1001","MYAREA",1)
END
*/

/* doppelganger quest: if PC enters tower for the first time after Sarevok's defeat, quest will "jump start"  ONLY if PC doesn't have access to prison / were to the prison already */

IF
	GlobalGT("DukeThanks","GLOBAL",0)
	Global("bsPrisonEntry","GLOBAL",0)
	Global("bsGavePrisonPass","GLOBAL",0)
	Global("bsJumpStartDGQuest","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("bsJumpStartDGQuest","GLOBAL",1)
END


//Doppelgangerquest: doppelgangers guards are gone after fumes are spread with the tanner's help */
/* all Doppelgangers are dead: detection */
IF
	GlobalGT("bsDoppelgangerInTower","GLOBAL",1)
	GlobalLT("bsDoppelgangerInTower","GLOBAL",5)
	NumDead("bsdopp07",5) //found all already
THEN
	RESPONSE #100
		DisplayStringHead(Player1,@11022)
		SetGlobal("bsDoppelgangerInTower","GLOBAL",5)
END

/* create doppelgangers dependening on how many the player already found: */

IF
	Global("bsDoppelgangerInTower","GLOBAL",4)
	NumDead("bsdopp07",4) 
	Global("bsDoppelgangerQuestSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerQuestSpawn","MYAREA",1)
		CreateCreature("bsdopp07",[2642.1704],6)
END
IF
	Global("bsDoppelgangerInTower","GLOBAL",4)
	NumDead("bsdopp07",3) 
	Global("bsDoppelgangerQuestSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerQuestSpawn","MYAREA",1)
		CreateCreature("bsdopp07",[2642.1704],6)
		CreateCreature("bsdopp07",[2744.1776],6)
END

IF
	Global("bsDoppelgangerInTower","GLOBAL",4)
	NumDead("bsdopp07",2) 
	Global("bsDoppelgangerQuestSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerQuestSpawn","MYAREA",1)
		CreateCreature("bsdopp07",[2642.1704],6)
		CreateCreature("bsdopp07",[2744.1776],6)
		CreateCreature("bsdopp07",[2850.1705],6)
END

IF
	Global("bsDoppelgangerInTower","GLOBAL",4)
	NumDead("bsdopp07",1) 
	Global("bsDoppelgangerQuestSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerQuestSpawn","MYAREA",1)
		CreateCreature("bsdopp07",[2642.1704],6)
		CreateCreature("bsdopp07",[2744.1776],6)
		CreateCreature("bsdopp07",[2850.1705],6)
		CreateCreature("bsdopp07",[2896.1806],6)
END

IF
	Global("bsDoppelgangerInTower","GLOBAL",4)
	!Dead("bsdopp07") //did find none so far
	Global("bsDoppelgangerQuestSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerQuestSpawn","MYAREA",1)
		CreateCreature("bsdopp07",[2642.1704],6)
		CreateCreature("bsdopp07",[2744.1776],6)
		CreateCreature("bsdopp07",[2850.1705],6)
		CreateCreature("bsdopp07",[2896.1806],6)
		CreateCreature("bsdopp07",[3015.1846],6)
END


//Doppelgangerquest: spawn real guards 
IF
	GlobalGT("bsDoppelgangerInTower","GLOBAL",0)
	GlobalLT("bsDoppelgangerInTower","GLOBAL",10)
	Global("bsDoppelgangerSpawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerSpawn","MYAREA",1)
		CreateCreature("bsdpgrd1",[2779.1677],6) //guard in front of barracks
		CreateCreature("bsdpgrd1",[4425.852],6)
		CreateCreature("bsdpgrd1",[3338.2408],6)
		CreateCreature("bsdpgrd1",[700.2337],6)
		CreateCreature("bsdpgrd1",[4275.1114],12)
END

//Doppelgangerquest: spawn doppelgangers
IF
	GlobalGT("bsDoppelgangerInTower","GLOBAL",0)
	GlobalLT("bsDoppelgangerInTower","GLOBAL",4)
	Global("bsDoppelgangerSpawn","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerSpawn","MYAREA",2)
		CreateCreature("bsdpgrd5",[777.1563],6)
		CreateCreature("bsdpgrd5",[1981.1259],0)
		CreateCreature("bsdpgrd5",[1532.1971],12)
		CreateCreature("bsdpgrd5",[3902.1287],0)
END


//Doppelgangerquest: Doppelgangers in barracks will be gone after fight.
IF
	Global("bsDoppelgangerInTower","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("bsDoppelgangerInTower","GLOBAL",3)
END

//Doppelgangerquest:
/* create guest that talks about tanner's stink */
IF
	PartyHasItem("bsdopdr")
	GlobalGT("bsDoppelgangerInTower","GLOBAL",2)
	Global("bsCreateDGCivilian","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bsdpciv",[2786.1739],4)
		SetGlobal("bsCreateDGCivilian","MYAREA",1)
END

/* Chapter 7, before palace scene : PC is fugitive */
// spawn special guards
IF
    Global("Chapter","GLOBAL",%tutu_chapter_7%)
    Global("bs_Capture1000","MYAREA",0)
    Global("DukeThanks","GLOBAL",0)
    Global("ENDOFBG1","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("bs_Capture1000","MYAREA",1)
		CreateCreature("bsch7grd",[2779.1677],6) //guard in front of barracks
		CreateCreature("bsch7grd",[1981.1259],0) //guard left of treasury
		CreateCreature("bsch7grd",[1630.1227],0) //guard on pallisade west
		CreateCreature("bsch7grd",[4429.855],0) //guard on pallisade northeast
		CreateCreature("bsch7grd",[4615.1498],0) //guard on pallisade east
		CreateCreature("bsch7grd",[917.2309],0) //guard on pallisade southwest
END

// spawn FF Enforcers either for: PC did not reveal doppelgangers in the seatower, or: encounter with commander is done
IF
    Global("Chapter","GLOBAL",%tutu_chapter_7%)
    Global("bs_Capture1000","MYAREA",1)
    Global("DukeThanks","GLOBAL",0)
    Global("ENDOFBG1","GLOBAL",0)
	OR(2)
		Global("bs_CityKnowsBSTDoppel","GLOBAL",0) //PC didn't finish reveal doppelgangers in tower
		GlobalGT("bs_TowerArrestCh7","GLOBAL",1) //PC did help and already met commander once
THEN
    RESPONSE #100
        SetGlobal("Capture100","GLOBAL",2)
        CreateCreature("FFHUNT",[1964.1272],6)  // Flaming Fist Enforcer
        CreateCreature("FFHUNT",[1913.1327],6)  // Flaming Fist Enforcer
END


/* spawn Lenard: Missing Monk quest */
IF
	Global("bsCreateLenard","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateLenard","MYAREA",1)
		CreateCreature("bslenard",[1871.1435],15)
END


/* spawn Klaus after he was kicked out of the inn */
IF
	Global("bsRabbitQuest","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("bsRabbitQuest","GLOBAL",4)
		CreateCreature("bstq004",[1523.1794],14)
END

/* Klaus conjurs the vampiric rabbit */
IF
	Global("bsRabbitQuest","GLOBAL",6)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		SetGlobal("bsRabbitQuest","GLOBAL",7)
		ActionOverride("bstq004",ForceSpellPoint([1523.1794],FLASHY_2))
		Wait(2)
		CreateCreature("bsvprab",[1523.1794],14)
		Wait(1)		
		EndCutSceneMode()
END

//all rabbit quest cres leave area
IF
	Global("bsRabbitQuest","GLOBAL",8)
THEN
	RESPONSE #100
		ActionOverride("bstq004",EscapeArea())
		ActionOverride("bstq007",EscapeArea())
		ActionOverride("bstq008",EscapeArea())
		SetGlobal("bsRabbitQuest","GLOBAL",9)
END

/* Help Shuck's brother: detection whether PC left the top floor */
IF
	Global("bsShucksBrother","GLOBAL",4)
THEN
	RESPONSE #100 
		SetGlobal("bsShucksBrother","GLOBAL",5)
END



/* "Lord Dlusker's Tomb Visit" quest broken */
IF
	Global("bs_LadyDluskersPlea","GLOBAL",99)
THEN
	RESPONSE #100
		EraseJournalEntry(@931)
		EraseJournalEntry(@932)
		EraseJournalEntry(@933)
		EraseJournalEntry(@934)
		EraseJournalEntry(@935)
		AddJournalEntry(@938,QUEST_DONE)
		SetGlobal("bs_LadyDluskersPlea","GLOBAL",100)
END


// Tannery door
IF
    TimeOfDay(NIGHT)
    !Global("bsLockTannerDoor","MYAREA",1)
    OpenState("DOOR 15",TRUE)
THEN
    RESPONSE #100
        CloseDoor("DOOR 15")
END

IF
    TimeOfDay(NIGHT)
    !Global("bsLockTannerDoor","MYAREA",1)
    OpenState("DOOR 15",FALSE)
THEN
    RESPONSE #100
        Lock("DOOR 15")
        SetGlobal("bsLockTannerDoor","MYAREA",1)
END

IF
    TimeOfDay(DAY)
    !Global("bsLockTannerDoor","MYAREA",0)
THEN
    RESPONSE #100
        SetGlobal("bsLockTannerDoor","MYAREA",0)
        Unlock("DOOR 15")
END
