/* Book Of the Planes bsalgbk.bcs */

IF
	Clicked([ANYONE])
	Range(LastTrigger,15)
	Global("bsPlaneBookCreation","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bsalgbk",[841.785],0)
		SetGlobal("bsPlaneBookCreation","MYAREA",1)
END

IF
	InMyArea("bsalgbk")
	Global("bsPlaneBookCreation","MYAREA",1)
THEN
	RESPONSE #100
		ActionOverride("bsalgbk",StartDialogueNoSet(Player1))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,15)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11007)
END

IF
	!InMyArea("bsalgbk")
	Global("bsPlaneBookCreation","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("bsPlaneBookCreation","MYAREA",0)
END