IF
	Clicked([ANYONE])
	Range(LastTrigger,30)
	GlobalLT("bsPrisonMyconiziden","GLOBAL",3)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11009) //The corner is damp, and the spore colony is growing in it, covering half of the wall.
END

IF
	Clicked([ANYONE])
	Range(LastTrigger,30)
	Global("bsPrisonMyconiziden","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("bsPrisonMyconiziden","GLOBAL",4)
		DisplayStringHead(Myself,@11014) //~This seems to be the corner the soldier mentioned. Parts of the spore colony still cover half of the wall. You could easily clear the corner with your weapons.~
END




IF
	Clicked([ANYONE])
	Range(LastTrigger,30)
	Global("bsPrisonMyconiziden","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("bsPrisonMyconiziden","GLOBAL",5)
		ActionOverride("bspspore",DestroySelf())
		DisplayStringHead(Myself,@11010) //~Removing the remains of the spore colony reveils an opening in the walls.~
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,30)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@11007)
END
