IF
	Global("bsDoppelgangerQuest","GLOBAL",8)
THEN
	RESPONSE #100
		ActionOverride("bsstgc",JumpToPoint([799.448]))
		SmallWait(1)
		ActionOverride("bsstgc",MoveToPointNoInterrupt([755.404]))
		CreateCreature("bstrmage",[702.348],0)
		ActionOverride("bsstgc",Face(6))
		ActionOverride("bstrmage",SetNumTimesTalkedTo(1))
		SetGlobal("bsDoppelgangerQuest","GLOBAL",9)
		CreateCreature("bsdpgrd1",[322.522],12)
		CreateCreature("bsdpgrd1",[488.594],12)
		CreateCreature("bsdpgrd1",[511.383],12)
		CreateCreature("bsdpgrd1",[771.414],12)
		CreateCreature("bsdpgrd1",[661.296],12)
		CreateCreature("bsdpgrd2",[442.546],12)
		CreateCreature("bsdpgrd2",[422.435],12)
		CreateCreature("bsdpgrd2",[642.445],12)
		CreateCreature("bsdpgrd3",[610.368],12)
END

/* Doppelganger quest ended, also because PC didn't want to help any more or timer run out: restore original situation in barracks */
IF
	GlobalGT("bsDoppelgangerInTower","GLOBAL",9)
	Global("bsDoppelgangerQuestFinished","MYAREA",0)
THEN
	RESPONSE #100
		ActionOverride("bsstgc",MoveToPointNoInterrupt([934.309]))
		ActionOverride("bsstgc",Face(0))
        	ActionOverride("bstrmage",DestroySelf())
		SetGlobal("bsDoppelgangerQuestFinished","MYAREA",1)
END

/* I see that one of my sarjeantes is about to deliver me yet another lost child. */
IF
	Global("bs_LostNecklaceQuest","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("bs_LostNecklaceQuest","GLOBAL",2)
		CreateCreature("bsqln001",[972.337],6) //lost girl
		CreateCreature("bsqln003",[1011.373],6) //Tower Guard
END

/* Mrs. Souter (mother) */
IF
	Global("bs_LostNecklace","MYAREA",3)
THEN
	RESPONSE #100
		SetGlobal("bs_LostNecklace","MYAREA",4)
		CreateCreature("bsqln002",[858.528],10) //Mrs. Souter
END
