/* innocent prison quest - prisoner dies */
IF
	Global("bs_KnowsPrisonerIntrigue","GLOBAL",7)
	Global("bsKillMalastair","MYAREA",0)
	InMyArea("bspris06")
	!Dead("bspris06")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ActionOverride("bspris06",TakePartyItem("bspris6b"))
		ActionOverride("bspris06",DestroyItem("bspris6b"))
		ActionOverride("bspris06",Kill(Myself))
		ReputationInc(-1)
		EraseJournalEntry(@100094)
		EraseJournalEntry(@100097)
		AddJournalEntry(@100096,QUEST_DONE)
		SetGlobal("bsKillMalastair","MYAREA",1)
		SetInterrupt(TRUE)
END

/* Spawn characters: prison guards, prisoners, Sahuagin Scout */
IF
	Global("bsCreateGuards","MYAREA",0)
THEN
	RESPONSE #100
        SetInterrupt(FALSE)
 	 	SetGlobal("bsCreateGuards","MYAREA",1)
		CreateCreature("bsprgrd2",[603.531],14)
		CreateCreature("bssahu04",[636.528],14)
		CreateCreature("bspris01",[445.435],15)
		CreateCreature("bspris02",[1135.428],3)
		CreateCreature("bspris03",[1020.333],3)
		CreateCreature("bspris04",[905.261],3)
		CreateCreature("bspris05",[771.176],3)
		CreateCreature("bspris06",[160.324],14)
        SetInterrupt(TRUE)
END

/* second guard will only spawn for normal quest path, not if PC enters first time after Sarevok is dead */
IF
	Global("bsJumpStartDGQuest","GLOBAL",0)
	Global("bsCreateGuards","MYAREA",1)
THEN
	RESPONSE #100
 	 	SetGlobal("bsCreateGuards","MYAREA",2)
		CreateCreature("bsprgrd1",[731.477],0)
END

/* move Sahuagin into cell after dialogue */

IF
	GlobalGT("bsPrisonEntry","GLOBAL",0)
	!Exists("bssahu04")
	!Dead("bssahu04")
	Global("bsMoveSahuagin","MYAREA",0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
 	 	SetGlobal("bsMoveSahuagin","MYAREA",1)
		CreateCreature("bssahu04",[457.603],10)
		SetInterrupt(TRUE)
END

/* group (re)entered prison - close and lock all doors */
IF
	InMyArea(Player1)
	Global("bs_PCWasInPrisonArea","GLOBAL",0)
THEN
	RESPONSE #100
		CloseDoor("Door 01")
		CloseDoor("Door 02")
		CloseDoor("Door 03")
		CloseDoor("Door 04")
		CloseDoor("Door 05")
		CloseDoor("Door 06")
		CloseDoor("Door 07")
		Wait(1)
		Lock("Door 01")
		Lock("Door 02")
		Lock("Door 03")
		Lock("Door 04")
		Lock("Door 05")
		Lock("Door 06")
		Lock("Door 07")
		SetGlobal("bs_PCWasInPrisonArea","GLOBAL",1)
END

/* start spore colony quest (leads to noticing the secret passage) */

IF
	GlobalGT("bsPrisonEntry","GLOBAL",1)
	Global("bsSpawnMyconiziden","MYAREA",0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		TriggerActivation("Travbs1010",FALSE) //prevent player to leave the area before spawn is completed. This is a safety measure due to glitches in the EE
		CreateCreature("bspspore",[427.149],15)
		SetGlobal("bsSpawnMyconiziden","MYAREA",1)
		SetInterrupt(TRUE)
END
IF
	Global("bsSpawnMyconiziden","MYAREA",1)
	DifficultyGT(EASIEST)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		CreateCreature("icmyc01",[602.221],14)
		SetGlobal("bsSpawnMyconiziden","MYAREA",2)
		SetInterrupt(TRUE)
END
IF
	Global("bsSpawnMyconiziden","MYAREA",2)
    DifficultyGT(NORMAL)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		CreateCreature("icmyc01",[513.231],14)
		SetGlobal("bsSpawnMyconiziden","MYAREA",3)
		SetInterrupt(TRUE)
END
IF
	InMyArea("bspspore")
    Global("bsPrisonMyconiziden","GLOBAL",0)
THEN
    RESPONSE #100
		SetInterrupt(FALSE)
		TriggerActivation("Travbs1010",TRUE)
        SetGlobal("bsPrisonMyconiziden","GLOBAL",1)
		SetInterrupt(TRUE)
END

/* remove 1st prison guard after PC is gone after dialogue */

IF
	GlobalGT("bsDoppelgangerQuest","GLOBAL",1)
	InMyArea("bsprgrd1")
	Global("bsDestroybsprgrd1","MYAREA",0)
THEN
	RESPONSE #100
		ActionOverride("bsprgrd1",DestroySelf())
 	 	SetGlobal("bsDestroybsprgrd1","MYAREA",1)
END


/* deactivate travel trigger to Seacave */
IF
	Global("bsCloseSeaExit","MYAREA",0)
THEN
	RESPONSE #100
		TriggerActivation("travbs0200",FALSE)
		TriggerActivation("bs0200ex",TRUE)
		SetGlobal("bsCloseSeaExit","MYAREA",1)
END

/* remove info trigger and open travel trigger once the opening is discovered */
IF
	Global("bsPrisonMyconiziden","GLOBAL",5)
THEN
	RESPONSE #100
		TriggerActivation("travbs0200",TRUE)
		TriggerActivation("bs0200ex",FALSE)
		SetGlobal("bsPrisonMyconiziden","GLOBAL",6)
END

/* Halfslinger will be gone after interrogation */

IF
	Global("bsInquisitorsWork","GLOBAL",3)
	InMyArea("yshafslg")
THEN
	RESPONSE #100
		ActionOverride("yshafslg",DestroySelf())
END

/* Spawn Shuck - "Help Shuck's Brother in Nashkel", "Smugglers in the Seatower" */ 
IF
	OR(3)
		Global("bsMissingMonk","GLOBAL",4)
		Global("bsMissingMonk","GLOBAL",5)
		Global("bsMissingMonk","GLOBAL",10)
	Global("bsCreateShuck","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bsshuck",[603.362],14)
 	 	SetGlobal("bsCreateShuck","MYAREA",1)
END

/* spawn interrogator after talking to Shuck */ 
IF
	GlobalGT("bsShucksBrother","GLOBAL",0)
	Global("bsInquisitorsWork","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("bsInquisitorsWork","GLOBAL",1)
		CreateCreature("yshafslg",[656.480],6)
END

/* Halfslinger will start dialogue */
IF
	Global("bsInquisitorsWork","GLOBAL",1)
	InMyArea("yshafslg")
THEN
	RESPONSE #100
		ActionOverride("yshafslg",Dialogue([PC]))
END

/* detect spore colony dead */
IF
	GlobalLT("bsPrisonMyconiziden","GLOBAL",3)
	Dead("bspspore")
THEN
	RESPONSE #100
        EraseJournalEntry(@753)
        AddJournalEntry(@754,QUEST)
 	 	SetGlobal("bsPrisonMyconiziden","GLOBAL",3)
END

/* Sahuagin will die eventually */
IF
	GlobalGT("bsSeaCaveOpen","GLOBAL",0)
	Global("bsPrisonSahuaginGone","MYAREA",0)
	!Dead("bssahu04")
THEN
	RESPONSE #100
		ActionOverride("bssahu04",Kill(Myself))
 	 	SetGlobal("bsPrisonSahuaginGone","MYAREA",1)
END

/* bandit prisoner will be gone after note was placed */
IF
	Global("bs_BanditHiddenGold","GLOBAL",4)
	InMyArea("bspris03")
THEN
	RESPONSE #100
		ActionOverride("bspris03",DestroySelf())
		SetGlobal("bs_BanditHiddenGold","GLOBAL",5)
END

/* innocent  prisoner will be gone after evidence was handed over */
IF
	GlobalGT("bs_KnowsPrisonerIntrigue","GLOBAL",7)
	InMyArea("bspris06")
THEN
	RESPONSE #100
		ActionOverride("bspris06",DestroySelf())
END
