// Open the secret door
IF
	Global("bsSeaCaveOpen","GLOBAL",3)
THEN
	RESPONSE #100
		TriggerActivation("Travbs0200",TRUE)
		Unlock("DOOR 01")
		OpenDoor("DOOR 01")
		SetGlobal("bsSeaCaveOpen","GLOBAL",4)
END


//Deactivate hidden door travel trigger
IF
	GlobalLT("bsSeaCaveOpen","GLOBAL",3)
	Global("bsHideSecretDoor","MYAREA",0)

THEN
	RESPONSE #100
		TriggerActivation("Travbs0200",FALSE)
		SetGlobal("bsHideSecretDoor","MYAREA",1)
END

// Failsafe: if glitch happens, reopen the secret door
IF
	Global("bsSeaCaveOpen","GLOBAL",4)
	OpenState("DOOR 01",FALSE)
THEN
	RESPONSE #100
		TriggerActivation("Travbs0200",FALSE)
		SetGlobal("bsSeaCaveOpen","GLOBAL",3)
END
