//Area script of YS0119.are, catacombs.


/* Remove Fuller and Muck */
IF
	OR(2)
		GlobalGT("bsClearedCatacombs","GLOBAL",20)
		Global("bs_RemoveMonks","MYAREA",1)
	!Global("bs_RemoveMonks","MYAREA",2)
THEN
	RESPONSE #100
		ActionOverride("bsrsd06",DestroySelf())
		ActionOverride("bsrsd07",DestroySelf())
		SetGlobal("bs_RemoveMonks","MYAREA",2)
END

/* journal entry when key is found */
IF
	PartyHasItem("bscckey")
	Global("bsClearedCatacombs","GLOBAL",3)
THEN
	RESPONSE #100
		AddJournalEntry(@940,QUEST)
		SetGlobal("bsClearedCatacombs","GLOBAL",4)
END

/* Place restless Dead into area: upon entering area first time. */

IF
	Global("bs_SpawnSkeletons","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("ysrstdd1",[364.665],2)
		CreateCreature("ysrstdd1",[479.1054],0)
		CreateCreature("ysrstdd1",[1238.854],0)
		CreateCreature("ysrstdd2",[1306.963],2)
		CreateCreature("ysrstdd2",[311.610],0)
		CreateCreature("ysrstdd2",[369.912],0)
		CreateCreature("ysrstdd3",[1340.950],2)
		CreateCreature("ysrstdd3",[577.897],0)
		CreateCreature("ysrstdd3",[235.766],0)
		CreateCreature("doomgu",[1392.1029],2)
		CreateCreature("doomgu",[203.470],2)
		SetGlobal("bs_SpawnSkeletons","MYAREA",1)
END

/* journal entry when door is opened */
IF
	OpenState("Door 01",TRUE)
	GlobalLT("bsClearedCatacombs","GLOBAL",6)
THEN
	RESPONSE #100
		EraseJournalEntry(@940)
		EraseJournalEntry(@942)
		AddJournalEntry(@941,QUEST)
		SetGlobal("bsClearedCatacombs","GLOBAL",6)
END

/* journal entry when scroll is found */
IF
	PartyHasItem("bsrsd07")
	GlobalLT("bsClearedCatacombs","GLOBAL",10)
THEN
	RESPONSE #100
		EraseJournalEntry(@946)
		AddJournalEntry(@947,QUEST)
		SetGlobal("bsClearedCatacombs","GLOBAL",10)
END

/* Muck should drop key */
IF 
	InMyArea("bsrsd06")
	Global("bs_MuckDropKey","MYAREA",0)
THEN
	RESPONSE #100
		ActionOverride("bsrsd06",DropInventory())
		SetGlobal("bs_MuckDropKey","MYAREA",1)
END

/* spawn Fuller */
IF
	GlobalLT("bsClearedCatacombs","GLOBAL",17)
	Global("bs_CreateFuller","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bs_CreateFuller","MYAREA",1)
		CreateCreature("bsrsd07",[1069.1093],14)
END

/* in case Fuller was killed while battling undead after banning ritual */
IF
	Global("bs_CreateFuller","MYAREA",1)
	Global("bsTalkedToRestlessDead","GLOBAL",10)
	GlobalLT("bsClearedCatacombs","GLOBAL",18)
	InMyArea("bsrsd07")
	Dead("bsrsd07")
THEN
	RESPONSE #100
		AddJournalEntry(@951,QUEST)
		SetGlobal("bs_CreateFuller","MYAREA",2)
END

/* in case Fuller was killed before banning the undead */
IF
	Global("bs_CreateFuller","MYAREA",1)
	GlobalLT("bsClearedCatacombs","GLOBAL",10)
	InMyArea("bsrsd07")
	Dead("bsrsd07")
THEN
	RESPONSE #100
		AddJournalEntry(@944,QUEST)
		SetGlobal("bs_CreateFuller","MYAREA",2)
END

/* journal entry after banning the KotD in case Fuller is dead */
IF
	Global("bs_CreateFuller","MYAREA",2)
	Global("bsTalkedToRestlessDead","GLOBAL",10)
	GlobalLT("bsClearedCatacombs","GLOBAL",17)
	Dead("bsrsd07")
THEN
	RESPONSE #100
		EraseJournalEntry(@941)  
		EraseJournalEntry(@942) 
		EraseJournalEntry(@946)
		AddJournalEntry(@950,QUEST)
		SetGlobal("bsClearedCatacombs","GLOBAL",17)
END
