

/* Doppelganger quest */
/* create commoner Docks, deactivate original door info trigger, set mapnote for tailor shop */
IF
	Global("bsCreateCommoner","MYAREA",0)
THEN
	RESPONSE #100
  		AddMapNote([4290.390],@38)
//		Unlock("DOOR 01")
//		OpenDoor("DOOR 01")
		TriggerActivation("InfoHouse",FALSE)
		SetGlobal("bsCreateCommoner","MYAREA",1)
		CreateCreature("bscommw1",[4090.600],0)
		Continue()
END


/* 5th smuggler quest: place barrel inside container */
/* BSBarrel01 */
IF
	Global("bsSmugglerQuest","GLOBAL",21)
	!Dead("bssmgl02")
	Global("bs_PlaceSmugglerBarrel","MYAREA",0)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("bs_PlaceSmugglerBarrel","MYAREA",1)
		ActionOverride("BSBarrel01",CreateItem("bssmq008",0,0,0))
		Continue()
END
/* remove barrel if PC split with smugglers before taking it */
IF
	GlobalGT("bsSmugglerQuest","GLOBAL",40)
	HasItem("bssmq008","BSBarrel01")
	Global("bs_PlaceSmugglerBarrel","MYAREA",1)
THEN
	RESPONSE #100
		ActionOverride("BSBarrel01",DestroyItem("bssmq008"))
		SetGlobal("bs_PlaceSmugglerBarrel","MYAREA",2)
		Continue()
END

/* PC took barrel: set journal entry and start timer */
IF
    PartyHasItem("bssmq008")
	Global("bsSmugglerQuest","GLOBAL",21)
THEN
    RESPONSE #100
        EraseJournalEntry(@100143)
        AddJournalEntry(@100144,QUEST)
        SetGlobalTimer("bsSmugglerQuestTimer5","GLOBAL",ONE_DAY)
        SetGlobal("bsSmugglerQuest","GLOBAL",22)
END
