/* smuggler bonus quest */
/* in case player is in BG1 after Sarevok's death, quest will start/happen there. Can be finished now. */
IF
	!Dead("bssmgl02")
	GlobalLT("bsSmugglerQuestBonus","GLOBAL",6)
	Global("bsSmugglerQuest","GLOBAL",41)
	Global("bs_SpawnHolgerBonus","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("bssmglb2",[362.142],0) //Holger
		SetGlobal("bs_SpawnHolgerBonus","MYAREA",1)
		Continue()
END
/* correct quest variable (set it to 3 if <3, otherwise don't touch it */
/* only in SoD */
IF
	GlobalLT("bsSmugglerQuestBonus","GLOBAL",3)
	Global("bs_SpawnHolgerBonus","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("bsSmugglerQuestBonus","GLOBAL",3)
		SetGlobal("bs_SpawnHolgerBonus","MYAREA",2)
		Continue()
END

/* in case Holger gets killed - correct variables and journal entries */
IF
	Dead("bssmgl02")
	GlobalLT("bsSmugglerQuestBonus","GLOBAL",8)
THEN
	RESPONSE #100
		EraseJournalEntry(@100158)
		EraseJournalEntry(@100159)
		EraseJournalEntry(@100160)
		EraseJournalEntry(@100161)
		EraseJournalEntry(@100162)
		AddJournalEntry(@100163,QUEST_DONE)
		SetGlobal("bsWorkingWithSmugglers","GLOBAL",2)
		SetGlobal("bsSmugglerQuest","GLOBAL",51)
		Continue()
END
