//---------------------------------------------------------
// Area BS0128 - dead Tanarr'i
//---------------------------------------------------------
/*
IF
	AreaCheck("bs0128")
	Global("bsTalkToAlguineHFM","GLOBAL",3)
	Global("bsAlguineTan","GLOBAL",0)
	Dead("bstanar")
	Global("bsFreedUlf","GLOBAL",1) //after Ulf had his speech and went away
	OR(2) InMyArea("bsalgune") Global("bs_AlguineMovedOn","GLOBAL",0)
THEN
	RESPONSE #100
		JumpToPoint([785.383])
		ForceSpellRES("SPWI402",Myself)
		Wait(2)
		SetGlobal("bsAlguineTan","GLOBAL",1)
END
Global("bsAlguineTan","GLOBAL",1)
*/

IF
	AreaCheck("bs0128")
	Global("bsAlguineTan","GLOBAL",1)
	Global("bsAlguineTan_1","MYAREA",0)
THEN
	RESPONSE #100
		Wait(11)
//		ForceSpellRES("SPWI402",Myself)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		SetGlobal("bsAlguineTan_1","MYAREA",1)
END

IF 
	AreaCheck("bs0128")
	Global("bsAlguineTan","GLOBAL",1)
	Global("bsAlguineTan_1","MYAREA",1)
	!InMyArea("bsalgune")
THEN
	RESPONSE #100
		SetGlobal("bsAlguineTan","GLOBAL",2)
		CreateCreature("bsalgune",[785.383],2)
END

IF
	AreaCheck("bs0128")
	GlobalGT("bsAlguineTan","GLOBAL",1)
	Global("bsAlguineTan_1","MYAREA",1)
	InMyArea("bsalgune")
THEN
	RESPONSE #100
		SetGlobal("bsAlguineTan_1","MYAREA",2)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0128 - charname's second visit
//---------------------------------------------------------
IF
	AreaCheck("bs0128")
	Global("bsAlguineTan_2","MYAREA",1)
	Global("bsAlguineTan","GLOBAL",3)
THEN
	RESPONSE #100
		Wait(11)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		SetGlobal("bsAlguineTan","GLOBAL",4)
END

IF
	AreaCheck("bs0128")
	Global("bsAlguineTan","GLOBAL",4)
	!InMyArea("bsalgune")
THEN
	RESPONSE #100
		SetGlobal("bsAlguineTan","GLOBAL",5)
		CreateCreature("bsalgune",[785.383],2)
END

IF
	AreaCheck("bs0128")
	GlobalGT("bsAlguineTan","GLOBAL",4)
	Global("bsAlguineTan_2","MYAREA",1)
	InMyArea("bsalgune")
THEN
	RESPONSE #100
		SetGlobal("bsAlguineTan_2","MYAREA",2)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0129
//---------------------------------------------------------
IF
	AreaCheck("bs0129")
	Global("bsCreateAlguineFM1","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateAlguineFM1","MYAREA",1)
		IncrementGlobal("bsVisitedHalls","GLOBAL",1)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(2)
		CreateCreature("bsalgune",[581.523],2)
		Wait(1)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0130
//---------------------------------------------------------
IF
	AreaCheck("bs0130")
	Global("bsCreateAlguineFM2","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateAlguineFM2","MYAREA",1)
		IncrementGlobal("bsVisitedHalls","GLOBAL",1)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(2)
		CreateCreature("bsalgune",[926.772],2)
		Wait(1)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0131
//---------------------------------------------------------
IF
	AreaCheck("bs0131")
	Global("bsCreateAlguineFM3L","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateAlguineFM3L","MYAREA",1)
		IncrementGlobal("bsVisitedHalls","GLOBAL",1)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(2)
		CreateCreature("bsalgune",[463.213],2)
		Wait(1)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0133
//---------------------------------------------------------
IF
	AreaCheck("bs0133")
	Global("bsCreateAlguineFM4","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateAlguineFM4","MYAREA",1)
		IncrementGlobal("bsVisitedHalls","GLOBAL",1)
		CreateVisualEffectObject("SPDIMNDR",Myself)
//		Wait(2) //for some reason this needs to be removed or he won't spawn
		CreateCreature("bsalgune",[700.1078],8)
		Wait(1)
		DestroySelf()
END

//---------------------------------------------------------
// Area BS0134
//---------------------------------------------------------
IF
	AreaCheck("bs0134")
	Global("bsCreateAlguineFM5","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("bsCreateAlguineFM5","GLOBAL",1)
		CreateVisualEffectObject("SPDIMNDR",Myself)
		Wait(2)
		CreateCreature("bsalgune",[1479.1330],7)
		Wait(1)
		DestroySelf()
END
