/* script for followers of official baron - turn hostile if attacked via dialogue */
IF
    Allegiance(Myself,ENEMY)
    Global("bs0102_spawn_sahuagin02","MYAREA",0)
THEN
    RESPONSE #100
        SetGlobal("bs0102_spawn_sahuagin02","MYAREA",1)
END

IF
    OR(2)
        Global("bs_BaronDeal","GLOBAL",-1)
        Dead("bsisagb1")
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        Enemy()
END
