/* Doppelganger in mage's study dead: mage should initialize dialogue */
IF
	Global("bsDoppelgangerQuest","GLOBAL",6)
	Dead("bsdopp01")
	Global("bs_MageUsesMimicPowder","GLOBAL",0)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END

/* journal entry management "Ingredients for the Seatower Mage" */

IF
	Global("bsBlackPearlQuest","GLOBAL",2)
	Global("bsBroughtBelladonna","GLOBAL",2)
	Global("bsBroughtWolfpelt","MYAREA",1)
	Global("bsBroughtAnkheg","MYAREA",1)
THEN
	RESPONSE #100 
		EraseJournalEntry(@850)
		EraseJournalEntry(@851)
		EraseJournalEntry(@852)
		EraseJournalEntry(@853)
		EraseJournalEntry(@854)
		EraseJournalEntry(@855)
		EraseJournalEntry(@857)
		AddJournalEntry(@856,QUEST_DONE)
		SetGlobal("bsBlackPearlQuest","GLOBAL",3)
END


IF
	Global("bsMageUmberHulkPlate","MYAREA",2)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet([PC])
END


IF
	Global("bsMageUmberHulkPlate","MYAREA",3)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		TakePartyItemNum("bsplat02",1)
		TakePartyItemNum("POTN21",1)
		TakePartyItemNum("SCRL67",1)
		TakePartyItemNum("MISC42",1)
		DestroyItem("bsplat02")
		DestroyItem("POTN21")
		DestroyItem("SCRL67")
		DestroyItem("MISC42")
		GiveItemCreate("bsplat03",[PC],0,0,0)
		TakePartyGold(6000)
		DestroyGold(6000)
		EraseJournalEntry(@100178)
		AddJournalEntry(@100179,QUEST_DONE)
		SetGlobal("bsMageUmberHulkPlate","MYAREA",4)
		SetInterrupt(TRUE)
END
