// Conditions to turn red
IF
   OR(3)
	 Global("ysCallToArms","GLOBAL",1)
	 AttackedBy([GOODCUTOFF],DEFAULT)
	 Heard([ANYONE],2002)
  !Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Shout(2002)
		ChangeAIScript("ysreact",OVERRIDE)
END

IF
  Global("ysguard4IsMoving","GLOBAL",0)
THEN
  RESPONSE #100
  MoveToPoint([4568.1642])
END

IF
  Global("ysguard4IsMoving","GLOBAL",1)
THEN
  RESPONSE #100
  MoveToPoint([3329.2412])
END
