// Conditions to turn red
IF
  OR(2)
	 AttackedBy([GOODCUTOFF],DEFAULT)
	 Heard([ANYONE],2002)
  !Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Shout(2002)
		ChangeAIScript("ysreact",OVERRIDE)
END

// Normal actions

//walking around the kitchen
IF
  True()
THEN
  RESPONSE #20
    MoveToPoint([220.752])
  RESPONSE #20
    RandomTurn()
    Wait(10)
	RESPONSE #20
    RandomTurn()
  RESPONSE #20
    MoveToPoint([323.803])
  RESPONSE #20
    RandomTurn()
    Wait(3)
END
