/* sent by the King of the Restless Dead: change to script with Random Walk (also affects the skeletons out of the graves, but with no consequence other than that they attack a little slower */

IF
	GlobalGT("bsTalkedToRestlessDead","GLOBAL",8)
	Global("bs_PrepareForGreatFight","LOCALS",0)
THEN
	RESPONSE #100
		ChangeAIScript("ysrstde2",OVERRIDE)
END



// Safety check - should already be Enemy()
IF
  !Allegiance(Myself,ENEMY)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

// Load a target
IF
  Allegiance(Myself,ENEMY)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		Continue()
END

// Select my ranged weapon
IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  !Range(LastSeenBy(Myself),4)
THEN
  RESPONSE #100
    EquipRanged()
   	SmallWait(3)
    Continue()
END

// Select my melee weapon
IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
   	SmallWait(3)
   	Continue()
END

// Now attack
IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  Detect([GOODCUTOFF])
THEN
 RESPONSE #100
   AttackOneRound(LastSeenBy(Myself))
END
