
# ini section header is required to avoid false detection
[Metadata]

# Full name of the mod, without version number
Name = BS Balduran's Seatower

# Author name or nick, don't use email address
Author = Yovaneth, jastey, multiple others

# Short description of the mod, main goals, features etc
Description = BBS Balduran's Seatower Modification (BST) is a mod for BGT, BG:EE, and EET, adding a new area to Baldur's Gate City, with several larger and small quests and encounters inside the new city district as well as related additions to the existing areas.


# Web address of mod Homepage
Homepage = https://www.gibberlings3.net/mods/quests/baldurans-seatower/

#  Web address of mod dedicated forum or forum thread 
Forum = https://www.gibberlings3.net/forums/forum/213-baldurans-seatower/

# if you use Github.com (preferred hosting site), simply use github.com/AccountOrOrgName/RepositoryName    
# If you use other hosting sites, please check requirements and put direct download link  
Download = https://github.com/Gibberlings3/BS_Baldurans_Seatower

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order Category
Type = Quests

Before = ACBre, c#brage, c#brandock, EET_end

After = bg1re, c#endlessbg1, EET, JA#BGT_AdvPack, transitions
