/* chapter 7: teleport group in front of tower area exit */
IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)		
        ActionOverride("bscmdch7",DestroySelf())
		SmallWait(1)
        LeaveAreaLUAPanic("bs1000","",[519.140],9)
        LeaveAreaLUA("bs1000","",[519.140],9)
        ActionOverride(Player2,LeaveAreaLUA("bs1000","",[587.128],8))
        ActionOverride(Player3,LeaveAreaLUA("bs1000","",[527.185],8))
        ActionOverride(Player4,LeaveAreaLUA("bs1000","",[595.181],8))
        ActionOverride(Player5,LeaveAreaLUA("bs1000","",[534.251],8))
        ActionOverride(Player6,LeaveAreaLUA("bs1000","",[604.232],8))
        MultiPlayerSync()
        Wait(3)
        EndCutSceneMode()
END
